#!/bin/bash
###########
#This Tool has been made by ShadowVMX.
###########


if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]] || [[ -z $4 ]] ; then
echo " "
echo "$(tput setaf 1)--help for information."
echo " "
echo "$(tput setaf 2)[+] Version 0.5.0"
echo " "
echo "$(tput setaf 7)https://github.com/ShadowVMX"
echo " "
fi

case $1 in
        ("--help")
                   echo " "
                   echo "_________________________________________________________"
                   echo "_________________________________________________________"
                   echo " "
                   echo "$(tput setaf 2)[+] Encrypt your own directory in windows."
                   echo "$(tput setaf 7) "
                   echo "[OPTIONS]"
                   echo ""
                   echo "-n [Username] --> You can find it in /mnt/c/Users/[USERNAME]."
                   echo ""
                   echo "-d [Directory Name] --> You should to create it first."
                   echo ""
                   echo "$(tput setaf 1)[Encrypt] --> [*]Encrypted -n [Username] -e [D.Name]"
                   echo ""
                   echo "[Desencrypt] --> [*]Encrypted -n [Username] -d [D.Name]"
                   echo "$(tput setaf 7)"
                   echo "_________________________________________________________"
                   echo "_________________________________________________________"
                   echo " "
                ;;


        ("-n") cd /mnt/c/Users/$2/Desktop
        ;;
esac

case $3 in
        ("-e") mv /mnt/c/Users/$2/Desktop/$4/ ...
        ;;
        ("-d") mv /mnt/c/Users/$2/Desktop/.../ $4
        ;;
esac






